# syntax=docker/dockerfile:experimental
# CUDA development image for building sources
FROM nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04 as builder

# available options 3.8, 3.9, 3.10, 3.11
ARG PYTHON_VERSION=3.8
ARG TORCH_CUDA_VERSION=cu116
ARG TORCH_VERSION=1.13.1+${TORCH_CUDA_VERSION}
ARG TORCHVISION_VERSION=0.14.1+${TORCH_CUDA_VERSION}
ARG TORCHAUDIO_VERSION=0.13.1

# set this to nightly for picking the nightly version of ONNXRuntime-Training
ARG ORT_BUILD_TYPE=stable

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1

# Install and update tools to minimize security vulnerabilities
RUN apt update -y && apt install -y software-properties-common wget apt-utils patchelf git libprotobuf-dev protobuf-compiler cmake \
    git bash curl libturbojpeg exiftool ffmpeg poppler-utils \
    libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
    libharfbuzz-dev libfribidi-dev libxcb1-dev
RUN unattended-upgrade
RUN apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

# install miniconda (comes with python 3.10 default)
ARG BUILD_USER=authmetorch
ARG MINICONDA_PREFIX=/home/$BUILD_USER/miniconda3

ARG CONDA_URL=https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh
RUN curl -fSsL --insecure ${CONDA_URL} -o install-conda.sh && \
    /bin/bash ./install-conda.sh -b -p $MINICONDA_PREFIX && \
    $MINICONDA_PREFIX/bin/conda clean -ya && \
    $MINICONDA_PREFIX/bin/conda install -y python=${PYTHON_VERSION}

ENV PATH=$MINICONDA_PREFIX/bin:${PATH}

ARG PYTHON_EXE=$MINICONDA_PREFIX/bin/python

RUN $PYTHON_EXE -m pip install pip wheel ipython fire ninja
RUN $PYTHON_EXE -m pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116

# for dino prequisites
RUN $PYTHON_EXE -m pip install cython \
    pycocotools \
    submitit \
    git+https://github.com/cocodataset/panopticapi.git#egg=panopticapi \
    scipy \
    termcolor \
    addict \
    yapf==0.33.0 \
    timm \
    opencv-python

WORKDIR /code

CMD bash